import * as fs from "node:fs";
import * as path from "node:path";
import type { McpTool, ServerConfig } from "./types.js";

// ── README Generation ────────────────────────────────────────

export function generateReadme(name: string, config: ServerConfig, tools: McpTool[]): string {
  const lines: string[] = [];

  lines.push(`# ${name} (MCP Server)`);
  lines.push("");
  if (config.url) lines.push(`**URL:** ${config.url}`);
  if (config.command) lines.push(`**Command:** ${config.command} ${(config.args ?? []).join(" ")}`);
  lines.push(`**Transport:** ${config.transport.toUpperCase()} | **Session:** @supi-${name}`);
  if (config.auth) lines.push(`**Auth:** ${config.auth.type}${config.auth.profile ? ` (profile: ${config.auth.profile})` : ""}`);
  lines.push("");

  if (config.triggers?.length > 0) {
    lines.push("## When to Use");
    for (const t of config.triggers) lines.push(`- ${t}`);
    lines.push("");
  }

  lines.push("## Tools");
  lines.push("");
  for (const tool of tools) {
    lines.push(`### ${tool.name}`);
    if (tool.description) lines.push(tool.description);
    if (tool.inputSchema) {
      const props = (tool.inputSchema as any).properties;
      if (props) {
        lines.push("**Parameters:**");
        for (const [pName, pDef] of Object.entries(props)) {
          const def = pDef as any;
          lines.push(`- \`${pName}\` (${def.type ?? "any"}) — ${def.description ?? ""}`);
        }
      }
    }
    lines.push("");
    lines.push("**Example:**");
    lines.push("```bash");
    lines.push(`mcpc --json @supi-${name} tools-call ${tool.name}`);
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by supipowers. Refresh with /supi:mcp refresh ${name}*`);

  return lines.join("\n");
}

export function writeReadme(basePath: string, name: string, content: string): void {
  const dir = path.join(basePath, "mcpc", name);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "README.md"), content);
}

export function writeToolsCache(basePath: string, name: string, tools: McpTool[]): void {
  const dir = path.join(basePath, "mcpc", name);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "tools.json"), JSON.stringify(tools, null, 2));
}

// ── Skill Generation ─────────────────────────────────────────

export function generateSkill(servers: Record<string, { tools: McpTool[] }>): string {
  const names = Object.keys(servers);
  const triggerList = names.map((n) => `$${n}`).join(", ");

  const lines: string[] = [];
  lines.push("---");
  lines.push("name: supi:mcpc");
  lines.push(`description: Use mcpc CLI to interact with MCP servers managed by supipowers. Triggers on: ${triggerList} or any mcpc tool invocation.`);
  lines.push("allowed-tools: Bash(mcpc:*)");
  lines.push("---");
  lines.push("");
  lines.push("# mcpc: MCP tools via supipowers");
  lines.push("");
  lines.push("Use the `mcpc_<name>` gateway tools to interact with MCP servers.");
  lines.push("Each server has a dedicated tool registered in your Available Tools.");
  lines.push("");
  lines.push("## Quick Reference");
  lines.push("");
  lines.push("The gateway tools accept `tool` (MCP tool name) and `args` (key-value object).");
  lines.push("Under the hood, they run: `mcpc --json @supi-<name> tools-call <tool> key:=value`");
  lines.push("");
  lines.push("## Available Servers");
  lines.push("");

  for (const [name, { tools }] of Object.entries(servers)) {
    lines.push(`### ${name} (@supi-${name})`);
    lines.push(`Tools: ${tools.map((t) => t.name).join(", ")}`);
    lines.push("");
  }

  return lines.join("\n");
}

export function writeSkill(basePath: string, content: string): void {
  const dir = path.join(basePath, "skills", "mcpc");
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "SKILL.md"), content);
}

// ── AGENTS.md ────────────────────────────────────────────────

const MARKER_START = "<!-- supipowers:mcpc:start -->";
const MARKER_END = "<!-- supipowers:mcpc:end -->";

function buildManagedSection(servers: Record<string, { description: string }>): string {
  const entries = Object.entries(servers);
  if (entries.length === 0) return "";

  const lines: string[] = [];
  lines.push(MARKER_START);
  lines.push("## MCP Servers (managed by supipowers)");
  lines.push("");
  lines.push("The following MCP servers are available via `$tag` or the `mcpc_<name>` tool:");
  lines.push("");
  for (const [name, { description }] of entries) {
    lines.push(`- **$${name}** — ${description}. Details: .pi/supipowers/mcpc/${name}/README.md`);
  }
  lines.push("");
  lines.push("Use `/supi:mcp` to manage servers. Invoke the `supi:mcpc` skill for usage patterns.");
  lines.push(MARKER_END);
  return lines.join("\n");
}

export function updateAgentsMd(cwd: string, servers: Record<string, { description: string }>): void {
  const agentsPath = path.join(cwd, "AGENTS.md");
  const section = buildManagedSection(servers);

  if (!fs.existsSync(agentsPath)) {
    if (section) fs.writeFileSync(agentsPath, section + "\n");
    return;
  }

  let content = fs.readFileSync(agentsPath, "utf-8");
  const startIdx = content.indexOf(MARKER_START);
  const endIdx = content.indexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing section
    const before = content.slice(0, startIdx);
    const after = content.slice(endIdx + MARKER_END.length);
    content = section ? before + section + after : before.trimEnd() + after;
  } else if (section) {
    // Append
    content = content.trimEnd() + "\n\n" + section + "\n";
  }

  fs.writeFileSync(agentsPath, content);
}
