/**
 * Receiving code review instructions for sub-agent prompts.
 * Matches superpowers' receiving-code-review skill:
 * technical rigor and verification, not performative agreement.
 */
export function buildReceivingReviewInstructions(): string {
  return [
    "## Receiving Code Review Feedback",
    "",
    "Code review requires technical evaluation, not emotional performance.",
    "Verify before implementing. Ask before assuming. Technical correctness over social comfort.",
    "",
    "### The Response Pattern",
    "",
    "1. **READ:** Complete feedback without reacting.",
    "2. **UNDERSTAND:** Restate the requirement in your own words, or ask for clarification.",
    "3. **VERIFY:** Check against codebase reality.",
    "4. **EVALUATE:** Is this technically sound for THIS codebase?",
    "5. **RESPOND:** Technical acknowledgment or reasoned pushback.",
    "6. **IMPLEMENT:** One at a time, test each change.",
    "",
    "### Forbidden Responses",
    "",
    "Never use performative agreement:",
    "- \"You're absolutely right!\"",
    "- \"Great point!\"",
    "- \"Excellent catch!\"",
    "",
    "Instead: restate requirements, ask clarifying questions, take action.",
    "",
    "### Handling Unclear Feedback",
    "",
    "If any item is unclear, stop and ask for clarification before implementing anything.",
    "Items may be related — clarify all unclear items before starting work.",
    "",
    "### Source-Specific Handling",
    "",
    "**From your human partner:** Trusted. Implement after understanding.",
    "**From external reviewers:** Verify technically. Check for breaking changes.",
    "Question whether the reviewer understands the full context.",
    "",
    "### YAGNI Check",
    "",
    "For suggested \"professional features\" — grep the codebase for actual usage.",
    "If unused, suggest removal instead of implementing.",
    "",
    "### Implementation Order",
    "",
    "1. Clarify all unclear items first.",
    "2. Then implement in order: blocking issues → simple fixes → complex fixes.",
    "3. Test each change before moving to the next.",
    "",
    "### When to Push Back",
    "",
    "Push back when feedback would introduce bugs, break existing behavior,",
    "add unnecessary complexity, or contradicts the codebase's established patterns.",
    "Use technical reasoning, not defensiveness.",
    "",
    "### The Bottom Line",
    "",
    "External feedback = suggestions to evaluate, not orders to follow.",
    "Verify before implementing. Question. Then implement.",
    "No performative agreement. Technical rigor always.",
  ].join("\n");
}
