export interface ReleaseNotesTemplateInput {
  tag: string;
  version: string;
  previousTag?: string;
  previousBody?: string;
  commitSubjects: string[];
}

export function extractTemplateSections(previousBody: string): string[] {
  return previousBody
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => /^##\s+/.test(line))
    .filter((line) => !/full changelog/i.test(line));
}

function defaultSections(): string[] {
  return [
    "## Highlights\n- TODO: summarize the most important outcomes for this release",
    "## Added\n- TODO",
    "## Changed\n- TODO",
    "## Fixed\n- TODO",
    "## Validation\n- [ ] typecheck\n- [ ] tests\n- [ ] build",
  ];
}

function commitSection(commitSubjects: string[]): string {
  const lines = commitSubjects.length > 0
    ? commitSubjects.map((subject) => `- ${subject}`)
    : ["- TODO: summarize commit-level changes"];

  return `## Included commits\n${lines.join("\n")}`;
}

export function buildReleaseNotesTemplate(input: ReleaseNotesTemplateInput): string {
  const sectionsFromPrevious = input.previousBody ? extractTemplateSections(input.previousBody) : [];

  const sections = sectionsFromPrevious.length > 0
    ? sectionsFromPrevious.map((heading) => `${heading}\n- TODO`)
    : defaultSections();

  const lines = [
    `# ${input.tag}`,
    sectionsFromPrevious.length > 0
      ? `_Draft template based on previous release structure${input.previousTag ? ` (${input.previousTag})` : ""}. Fill in details before publishing._`
      : "_Draft template generated by Supipowers. Fill in details before publishing._",
    ...sections,
    commitSection(input.commitSubjects),
  ];

  if (input.previousTag) {
    lines.push(`## Compare\n- ${input.previousTag}...${input.tag}`);
  }

  return `${lines.join("\n\n")}\n`;
}
